generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ArTelephonePrefix
    theme:            default

    fields:
      prefix: { name: Telephone Prefix }
      
      operator_type: { name: Connection Type }
      
      name: { name: Operator Name }
      
      geographic_location: { name: Geographic Location }

      never_mask_number: { name: Never Mask, help: "True for displaying the associated telephone number, without mask of last digits. Note that there is a global option in `app.yml` file for enabling or disabling masking of all telephone numbers, so this field is only for local special exclusions. " }

    list:
      title: Telephone Prefixes

      display: [=prefix, operator_type, geographic_location, name]

      filters: [prefix, operator_type, geographic_location, name]
      sort: [prefix, asc]

    edit:
      title: Telephone Prefix
      fields: [prefix, operator_type, name, geographic_location, never_mask_number]
